version: '4.33.1'
services:
  database:
    build:
      context: ./database
    image: udemyspring/database:latest
    ports:
      - 5432:5432
    container_name: udemyspring
    networks:
      - backend

networks:
  backend:
    driver: "bridge"